import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/common/Layout";
import Card from "../components/pages/Card";
import styles from "/styles/pages/home/Home.module.scss";
import Filters from "../components/common/Filters";
import React from "react";

const Home: NextPage = () => {
  return (
    <div className="home">
      <Head>
        <title>Gamely</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Filters />
        <div className={styles.content}>
          <div className={styles.container}>
            <div className={styles.gamesList}>
              <Card />
              <Card />
              <Card />
              <Card />
              <Card />
              <Card />
            </div>
          </div>
        </div>
      </Layout>
    </div>
  );
};

export default Home;
