import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/common/Layout";
import Card from "../components/pages/Card";
import styles from "/styles/pages/home/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className="home">
      <Head>
        <title>Gamely</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className={styles.gamesList}>
          <Card />
          <Card />
          <Card />
          <Card />
          <Card />
          <Card />
        </div>
      </Layout>
    </div>
  );
};

export default Home;
