import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from "../components/common/Layout";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Gamely</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        {/*<h1>Hello</h1>*/}
      </Layout>
    </div>
  )
}

export default Home
